# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djfractions.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('PR', 'Produce'), ('SP', 'Spices'), ('DY', 'Dairy'), ('MT', 'Meat'), ('FR', 'Refridgerated / Freezer'), ('BK', 'Baking'), ('BY', 'Bakery'), ('CN', 'Canned / Packaged')], max_length=2)),
                ('quantity', djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=2, limit_denominator=8, max_digits=4)),
                ('unitOfMeasure', models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz'), ('NA', 'none')], default='CP', max_length=2)),
                ('quantity_2', djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=2, limit_denominator=8, max_digits=4)),
                ('unitOfMeasure_2', models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz'), ('NA', 'none')], default='TB', max_length=2)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(to='mealplanner.Recipe')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Recipe'),
        ),
    ]
