# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=2, default=0, limit_denominator=8, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_2',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=2, default=0, limit_denominator=8, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unitOfMeasure',
            field=models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz'), ('NA', 'none')], default='CP', max_length=2),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unitOfMeasure_2',
            field=models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz'), ('NA', 'none')], default='TB', max_length=2),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
