# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_2',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=2, default=0, limit_denominator=8, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unitOfMeasure_2',
            field=models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz'), ('NA', 'none')], default='NA', max_length=2),
        ),
    ]
