# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0004_auto_20170309_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('unitOfMeasure', models.CharField(choices=[('CP', 'Cup'), ('TB', 'tbs'), ('TS', 'tsp'), ('LB', 'lb'), ('OZ', 'oz'), ('FO', 'fl oz')], default='CP', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='mealplanner.Ingredient'),
        ),
    ]
